"""Add profile_pic field to User model

Revision ID: 391dd8570426
Revises: 3deeffac6322
Create Date: 2023-06-17 08:54:31.119270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391dd8570426'
down_revision = '3deeffac6322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
